name = "Foo Bar"

[personal_info]
email = "foo@example.com"
phone = "555-555-5555"
github = "github.com/foo"

[[personal_info.other]]
item = "Foo"
url = "https://example.com"

[[personal_info.other]]
item = "Bar"

[objective]
objective = "objective"

[[professional_experience]]
organization = "organizationA"
location = "locationA"
position = "positionA"
start = "startA"
end = "endA"
experience = [
    "FooA",
    "BarA",
    "BazA",
]

[[professional_experience]]
organization = "organizationB"
location = "locationB"
position = "positionB"
start = "startB"
end = "endB"
experience = [
    "FooB",
    "BarB",
    "BazB",
]

[education]
school = "school"
location = "location"
major = "major"
graduation = "graduation"
extras = [
    "Foo",
    "Bar",
    "Baz",
]

[technologies]
technologies = [
    "Foo",
    "Bar",
    "Baz",
]

[[other_experience.projects]]
project_name = "Project Name"
url = "https://example.com"
description = "Description"

[cover_letter]
paragraphs = [
    "foo",
    "bar",
    "baz",
]
