# This workflow triggers a build of a private resume data repo
# Todo: put the resume repo in an environment variable

name: Trigger Resume Render

# Controls when the action will run. 
on:
  # Only trigger a build of the resume of the generator tests pass
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types: 
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Trigger render
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/spencewenski/resume/dispatches \
            -d '{"event_type":"repository_dispatch"}' \
            -H "Authorization: token ${{ secrets.API_TOKEN }}"
